#!/bin/bash

###############################################################################
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, 
#  - write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#   - See http://www.gnu.org/licenses/gpl.html
###############################################################################


# Varibles
SYSCONF_PATH='/pub/git/'               # Chemin vers la conf apache
SITE_AVAILABLE='repo-available'        # Site en attente
SITE_ENABLED='repo-enabled'            # Site activés


# Quel site ?
if [ -z ${1} ]; then
    echo "Which repository do you want to enable ?"
    for site in ${SYSCONF_PATH}/${SITE_AVAILABLE}/*; do
        echo -e "\t${site}" | sed -e "s,${SYSCONF_PATH}/${SITE_AVAILABLE}/,,g"
    done;
    echo -n "Name of the repository ? "
    read SITENAME
else
    SITENAME=${1}
fi

# Déjà activé ?
if [ -e ${SYSCONF_PATH}/${SITE_ENABLED}/${SITENAME} ]; then
    echo "This repository is already enabled!"
    exit 0
fi


# Présent ?
if ! [ -e ${SYSCONF_PATH}/${SITE_AVAILABLE}/${SITENAME} ]; then
    echo "This repository doesn't exist!"
    exit 1
fi


# Traitement :
ln -sf ${SYSCONF_PATH}/${SITE_AVAILABLE}/${SITENAME}/.git ${SYSCONF_PATH}/${SITE_ENABLED}/${SITENAME}.git
echo "Repository ${SITENAME} installed."
